info:
  contact: {}
  description: Go admin 测试
  title: Go admin 开发
  version: "1.0"
paths:
  /api/v1/public/user/login:
    post:
      description: 登录
      parameters:
      - description: 用户名
        in: formData
        name: name
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      responses:
        "200":
          description: '{"msg":"登录成功"}'
          schema:
            type: string
        "400":
          description: '{"msg":"登录失败"}'
          schema:
            type: string
      summary: 登录
      tags:
      - 用户管理
swagger: "2.0"
